CREATE TABLE GAME_PLAYER (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLAYER_NAME VARCHAR2(50),
    ATTEMPTS NUMBER,
    RESULT VARCHAR2(20)
);

INSERT INTO GAME_PLAYER (PLAYER_NAME, ATTEMPTS, RESULT)
VALUES ('Jugador Demo', 2, 'GANO');

COMMIT;

SELECT * FROM GAME_PLAYER;